### ISSUE TITLE
Cannot unpickle lieconv_model.pkl

### ISSUE THREAD

**Issue by SSHS-Han** [LZ0221/Lieconv-Tg#1]
To unpickle the file lieconv_model.pkl, I used the following code:
```
import pickle

with open('lieconv_model.pkl', 'rb') as f:
    data = pickle.load(f)
```

However, I got this error message:
Exception has occurred: UnpicklingError
A load persistent id instruction was encountered,
but no persistent_load function was specified.
  File "C:\Users\sshs2\Lieconv-Tg\models\Lieconv\main.py", line 5, in <module>
    data = pickle.load(f)
           ^^^^^^^^^^^^^^
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

After searching more about this, I got to know that custom classes were used in the pickle file and therefore cannot be unpickled. 
How can I solve this problem?

**Comment by LZ0221** [comment]
When saving models in PyTorch, I’m accustomed to using the .pkl extension, but a more common practice is to use .pt or .pth as the file suffix.
![微信截图_20240424155345](https://github.com/LZ0221/Lieconv-Tg/assets/93578697/7477fd98-da9a-446c-ace3-fa2209a5d959)
If you want to load the corresponding Lieconv model, you can use the following code.
![微信截图_20240424155848](https://github.com/LZ0221/Lieconv-Tg/assets/93578697/1a126632-078d-487b-9539-ce9fef03cb57)
